spring:
  application:
    name: bff
eureka:
  instance:
    appname: bff
    metadata-map:
      version: v1
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
    healthcheck:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  hystrix:
    enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
logging:
  file: logs/elk-stack.log
service:
  product:
    application:
      name: product-service
  discount:
    application:
      name: discount-service
  recommendation:
    defaultProducts: 
      - 7
      - 9
    application:
      name: recommendation-service
  availability:
    application:
      name: availability-service
      url: availability-service:8080
