spring:
  application:
    name: discount-service
  datasource:
    url: jdbc:mysql://mysql-discount-service:3306/discount-service?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: microservice-user
    password: kJkSzPj
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      show_sql: false
eureka:
  instance:
    appname: discount-service
    metadata-map:
      version: v1
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
    healthcheck:
      enabled: true
