spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: bff
          uri: lb://bff
          predicates:
            - Path=/product/**
        - id: monolith
          uri: lb://monolith
          predicates:
            - Path=/cart/**, /order/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/auth/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:8091/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/auth/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway-service
            client-secret: b0ac3d95-8201-4f4d-bd69-93cffdd83d8a
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
eureka:
  instance:
    appname: gateway-service
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
service:
  security:
    application:
      url: /auth
