spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: bff
          uri: lb://bff
          predicates:
            - Path=/product/**
        - id: monolith
          uri: lb://monolith
          predicates:
            - Path=/cart/**, /order/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/auth/realms/SpringBootKeycloak
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/SpringBootKeycloak
            user-name-attribute: paul
        registration:
          keycloak:
            client-id: gateway-service
            client-secret: sgd34bwfAbfSBPpe0r8gwbg
eureka:
  instance:
    appname: gateway-service
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
service:
  security:
    application:
      url: /auth
