spring:
  application:
    name: security-service
jwt:
  header: Authentication
  expires_in: 86400
  secret: sgd34bwfAbfSBPpe0r8gwbg

eureka:
  instance:
    appname: security-service
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
service:
  auth:
    url: http://localhost:8091/auth/realms/ecommerce/protocol/openid-connect/token
