spring:
  application:
    name: security-service
eureka:
  instance:
    appname: security-service
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
service:
  auth:
    url: http://keycloak:8080/auth/realms/ecommerce/protocol/openid-connect/token
logging:
  file: ELK/logs/elk-stack.log
