spring:
  profiles: 
    active: default
  application:
    name: statistic-service
  datasource:
    url: jdbc:mysql://mysql-statistic-service:3306/statistic?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: microservice-user
    password: kJkSzPj
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      show_sql: false
eureka:
  instance:
    appname: statistic-service
    metadata-map:
      version: v1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
server:
  port: 8090
