spring:
  application:
    name: statistic-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json: 
            value:
              default:
                type: com.epam.mentoring.model.StatisticMessage
            trusted:
              packages: com.epam.mentoring.model
eureka:
  instance:
    appname: statistic-service
    metadata-map:
      version: v1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
kafka:
  bootstrap-address: kafka-server:9092
  group-id: test-consumer-group
  topic: statistic-topic
server:
  port: 8090
