spring:
  profiles: 
    active: default
  application:
    name: statistic-service
  datasource:
    url: jdbc:mysql://localhost:3308/statistic?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: microservice-user
    password: kJkSzPj
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      show_sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.epam.mentoring.model.StatisticMessage
eureka:
  instance:
    appname: statistic-service
    metadata-map:
      version: v1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
kafka:
  bootstrapAddress: 'localhost:9092'
  topic: statistic-topic
server:
  port: 8090
