spring:
  application:
    name: statistic-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
eureka:
  instance:
    appname: statistic-service
    metadata-map:
      version: v1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9001/eureka
kafka:
  topic: statistic-topic
server:
  port: 8090
